openapi: 3.0.1
info:
  title: README parser Plugin
  description: Plugin for parsing a README.md from github repository, you will get a full text for forward a AI usage.
  version: 'v1'
servers:
  - url: http://localhost:8888
paths:
  /parse:
    post:
      operationId: parse
      summary: parse readme file via url from github repository.
      parameters:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTodoRequest'
      responses:
        "200":
          description: OK
components:
  schemas:

    addTodoRequest:
      type: object
      required:
      - url
      properties:
        url:
          type: string
          description: The url to the repo.
          required: true

      required:
      - todo_idx
      properties:
        todo_idx:
          type: integer
          description: The index of the todo to delete.
          required: true